<?php

// file_name|onmouseover_image|alt_attribute|additional_attribute

$navi=array();
$navi['admin']='admin.png||'.$lang['admin'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';       // admin
$navi['rooms']='rooms.png||'.$lang['rooms'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';       // rooms
$navi['profl']='profl.png||'.$lang['profile'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';     // profile
$navi['smile']='smile.png||'.$lang['smilies'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';     // smilies
$navi['tzone']='tzone.png||'.$lang['timezone'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';    // timezone
$navi['sound']='sound.png||'.$lang['sound'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';       // sound
$navi['color']='color.png||'.$lang['color'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';       // colors
$navi['exitt']='exitt.png||'.$lang['exitt'].'|onmouseover="op(this,7)" onmouseout="op(this,10)"';       // logout


// ACC. NUMBER - foreground and background colors

$bg['r']=0x4e;                       // bg color - RED
$bg['g']=0x88;                       // bg color - GREEN
$bg['b']=0xe0;                       // bg color - BLUE
$fg['r']=0xff;                       // fg color - RED
$fg['g']=0xff;                       // fg color - GREEN
$fg['b']=0xff;                       // fg color - BLUE

?>