<?php

/* filename = 'language.extension' */

$lang_files=array();

$lang_files[]='english.utf8';
$lang_files[]='bulgarian.utf8';
$lang_files[]='chinese.utf8';
$lang_files[]='croatian.utf8';
$lang_files[]='czech.utf8';
$lang_files[]='deutsch.utf8';
$lang_files[]='dutch.utf8';
$lang_files[]='georgian.utf8';
$lang_files[]='portuguese.utf8';
$lang_files[]='russian.utf8';
$lang_files[]='spanish.utf8';
$lang_files[]='swedish.utf8';

?>